### ISSUE TITLE
name: 3. Install mediawiki dependencies - needs updating

### ISSUE THREAD

**Issue by andrecastro0o** [TIBHannover/confiDent-Ansible-VMs#3]
https://github.com/TIBHannover/confiDent-Ansible-VMs/blob/f00982c0c3d62e6f011699f30ebeafae2be5fb60/ansible/roles/mediawiki/tasks/main.yml#L24
```
- name: 3. Install mediawiki dependencies
  shell: 
    cmd: composer install --no-dev
    chdir: '/var/www/html/mediawiki'
  become: no
  become_user: "{{ansible_ssh_user}}"
```

Obsolete: become_user: "{{ansible_ssh_user}}"  To be removed

Hardcoded dir should become variable: `chdir: '/var/www/html/mediawiki'` -> `chdir:  '{{ mediawiki_path }}'
`

Corrected: 
```
- name: 3. Install mediawiki dependencies
  shell: 
    cmd: composer install --no-dev
    chdir: '{{ mediawiki_path }}'
  become: no
 ```
